### import pyitlib

# HI GUYS 

Objectives of new presentations:

>Demonstration of MMMRWPC (or any of the new mods presented) of higher prediction stability over older techniques.


Incremental modifications done to Markov Blanket estimator algorithms:
- Cache of dependency calculation (not writable)
- Maybe use an statistics approach to fasten cache of dependency (not writable as its not invented yet - should be researched after first papers)
- M1(DONE): INTERLEAVING - Use of phase 2 after each iteration of phase 1 (writeable, missing a version of MMPC with only that modification)
- M2(DONE): Use of community creation technique only at phase 2 (writeable, missing version of MMPC with only that modification)
- M3(DONE): Selection of all nodes based on equal max dep-score (writeable, missing version of MMPC with only that mod)
- M1 & M2 (DONE)
- M1 & M3 (DONE)
- M2 & M3 (DONE)
- M1 & M2 & M3 (already done) (DONE)

-CREATE BASIC EXECUTION PIPELINE 
>RETRIEVE INITIAL RESULTS WITH PIPELINE

General modifications to be done>
- Add lambda functions new structure to dependency function, already researched below in this notebook
- Create benchmarking function using TRUE NEGATIVE RATE VS TRUE POSITIVES RATE (TNR VS TPR)

General annotations to new advance:
-Time of execution WILL NOT BE BENCHMARKED

## Second Appointment
- Results over 4 different artificial networks
- Mean, Max, Min, Var and PC and MB len for each test
- Work over presentation of graphics (DONE)
- Try first using 1 file per dataset type, then escalate to all files for s500 versions and finally test for S1000.

## Third Appointment
- Measure times and degree of dep calls made in each method.

In [29]:
import bz2
import pickle

In [38]:
with bz2.open("/home/a20114261/sdelrio/Network Packages/Processed Datasets/Child/Results/Child10_s5000_v4_niter_0.bz2","rb") as f:
    r = pickle.load(f)

In [39]:
r

[{'CPC': ['Node86@2', 'Node98@3'],
  'time': 1.48,
  'target': 'Node@93',
  'counter': {'degree_0': 199, 'degree_1': 10, 'degree_2': 2},
  'method': 'MMPC',
  'iter_n': 0,
  'failure': 0},
 {'CPC': ['Node102@2',
   'Node103@3',
   'Node119@3',
   'Node115@2',
   'Node105@5',
   'Node116@3',
   'Node120@2',
   'Node101@2',
   'Node106@2',
   'Node117@4',
   'Node114@3',
   'Node118@3'],
  'time': 327.27,
  'target': 'Node@112',
  'counter': {'degree_0': 199,
   'degree_1': 175,
   'degree_2': 828,
   'degree_3': 2385,
   'degree_4': 4935,
   'degree_5': 7553,
   'degree_6': 8699,
   'degree_7': 7588,
   'degree_8': 4994,
   'degree_9': 2442,
   'degree_10': 860,
   'degree_11': 206,
   'degree_12': 30,
   'degree_13': 2},
  'method': 'MMPC',
  'iter_n': 0,
  'failure': 0},
 {'CPC': ['Node108@3',
   'Node112@6',
   'Node119@3',
   'Node117@4',
   'Node111@5',
   'Node118@3'],
  'time': 38.93,
  'target': 'Node@105',
  'counter': {'degree_0': 199,
   'degree_1': 73,
   'degree_2': 191,
  

In [234]:
!pip install numba

You are using pip version 9.0.1, however version 19.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [4]:
from pyitlib import discrete_random_variable as drv

In [12]:
import random
a = [random.randint(0,10,) for x in list(range(0,10))]
b = [random.randint(0,10,) for x in list(range(0,10))]
c = [random.randint(0,10,) for x in list(range(0,10))]

In [15]:
drv.information_mutual_conditional(a,b,c)

array(0.9509775)

In [17]:
import dit

In [199]:

var_arr = [[random.randint(0,4) for x in list(range(0,1000))] for y in list(range(0,100))]

In [247]:
import random
import time
import numpy as np
import operator
from functools import reduce

In [21]:
import time
import numpy as np
t_start = time.time()
for i in range(0,1024):
  np_arr = np.asarray(var_arr)
  np_acc = np_arr.sum(axis=0)
  
time.time() - t_start


0.8337602615356445

In [22]:
t_start = time.time()
for i in range(0,1024):
  accumulator = np.zeros(1000)
  for j in range(0,len(var_arr)):
    for k in range(0,len(var_arr[j])):
      accumulator[k] += var_arr[j][k]
time.time() - t_start

7.153183937072754

In [41]:
def benchmark_f(f,params, n_iter):
    t_start = time.time()
    for i in range(0,n_iter):
        f(params)
    return time.time() - t_start

In [43]:
import operator
from functools import reduce
benchmark_f(lambda x:reduce(lambda y,z:y*z, x),var_arr[0],1024)

0.1629042625427246

In [ ]:
for i in range(0,len(vvTarget)):
    for j in range(0,len(vvXi)):
        for k in range(0,szCondVars):
            condValue = self.__get_cond_values(k,CondVars)
            flagData_arr = []
            flagData_arr.append(np.ones(len(Xi['data'])))
            
            for l in range(0,len(CondVars)):
                X_l = CondVars[l]

                op_x = self.__dep_dict_retriever(X_l,condValue[l])

                flagData_arr.append(op_x)

                        #op1 = dep_dict_retriever(TargetNode,vvTarget[i])
            flagData_arr.append(self.__dep_dict_retriever(TargetNode,vvTarget[i]))
                        #op2 = dep_dict_retriever(Xi,vvXi[j])
            flagData_arr.append(self.__dep_dict_retriever(Xi,vvXi[j]))

            flagDataCondVars = reduce(lambda x,y:x*y, flagData_arr)

            S[i][j][k]=np.sum(flagDataCondVars)

In [306]:
t_start = time.time()

S = np.zeros((3,4,2**4,7,1000))

flagDataAcum = []
for i in range(0,3):
    for j in range(0,4):
        for k in range(0,2**4):
            flagData_arr = []
            flagData_arr.append(var_arr[0])
            for l in range(0,4):
                flagData_arr.append(var_arr[1])
            flagData_arr.append(var_arr[2])
            flagData_arr.append(var_arr[3])
            
            #flagDataCondVars = reduce(lambda x,y:np.multiply(x,y), flagData_arr)
            
            #S[i][j][k]=np.sum(flagDataCondVars)
            S[i][j][k]=np.array(flagData_arr)
            
time.time()-t_start

0.15971755981445312

In [209]:
t_start = time.time()


for n in range(0,100):
    S = np.zeros((3,4,2**4))
    for n in range(0,1):
        flagDataAcum = []
        for i in range(0,3):
            for j in range(0,4):
                for k in range(0,2**4):
                    flagData_arr = []
                    flagData_arr.append(np.array(var_arr[i]))
                    for l in range(0,4):
                        flagData_arr.append(np.array(var_arr[l]))
                    flagData_arr.append(np.array(var_arr[j]))
                    flagData_arr.append(np.array(var_arr[k]))

                    flagDataCondVars = reduce(lambda x,y:x*y, flagData_arr)

                    S[i][j][k]=np.sum(flagDataCondVars)
            
print(time.time()-t_start)
S

11.931670665740967


array([[[482820., 408072., 415904., 396916., 276361., 264480., 301191.,
         267188., 303419., 263966., 271340., 272660., 270449., 326657.,
         283238., 263447.],
        [408072., 416340., 378740., 354824., 251299., 236898., 273999.,
         238286., 276667., 231624., 246934., 240728., 242167., 293575.,
         256134., 233209.],
        [415904., 378740., 431490., 367844., 246857., 241544., 279849.,
         242310., 286709., 239176., 256364., 245606., 246563., 297885.,
         253948., 244717.],
        [396916., 354824., 367844., 397836., 234937., 234126., 266909.,
         235372., 276443., 227532., 242868., 243980., 225361., 285273.,
         254518., 227757.]],

       [[408072., 416340., 378740., 354824., 251299., 236898., 273999.,
         238286., 276667., 231624., 246934., 240728., 242167., 293575.,
         256134., 233209.],
        [416340., 499878., 430694., 398770., 278491., 266166., 303963.,
         266366., 316787., 255434., 285158., 264422., 272849., 319

In [298]:
t_start = time.time()

def sum_mul_f(arr):
    return (lambda x:np.sum(reduce(lambda y,z:y*z, x),axis=0))(arr)

for n in range(0,100):
    #S = np.zeros((3,4,2**4,1+4+1+1,1000))
    #flagDataAcum = []
    #for i in range(0,3):
    #    for j in range(0,4):
    #        for k in range(0,2**4):
    #            flagData_arr = []
    #            flagData_arr.append(var_arr[i])
    #            for l in range(0,4):
    #                flagData_arr.append(var_arr[l])
    #            flagData_arr.append(var_arr[j])
    #            flagData_arr.append(var_arr[k])
    #            
    #            flagDataAcum.append(flagData_arr)
                #flagDataCondVars = reduce(lambda x,y:x*y, flagData_arr)
                
                #S[i][j][k]=flagDataCondVars}
                #S[i][j][k] = np.array(flagData_arr)
    flagDataAcum=[put_arr([x//(4*16),x//(16)%4,x%16]) for x in list(range(0,192))]
    flag_calc = *map(lambda x:np.sum(reduce(lambda y,z:y*z, np.array(x)),axis=0),flagDataAcum),
    S = np.asarray(flag_calc).reshape((3,4,16))
    #S = S.sum(axis=3)
            
print(time.time()-t_start)
S

10.992314100265503


array([[[546838, 451352, 473364, 455864, 313819, 300696, 314903, 336496,
         330380, 299897, 337327, 319740, 347310, 281412, 300181, 314320],
        [451352, 446956, 417830, 400950, 283661, 258292, 282751, 298332,
         288012, 251853, 304631, 293984, 317630, 239944, 263915, 276828],
        [473364, 417830, 482716, 419414, 290381, 267640, 287975, 307000,
         298514, 273561, 316503, 298378, 318364, 256104, 274809, 289524],
        [455864, 400950, 419414, 445474, 285471, 261464, 274417, 294396,
         289056, 261471, 306973, 280876, 311352, 248494, 263495, 279292]],

       [[451352, 446956, 417830, 400950, 283661, 258292, 282751, 298332,
         288012, 251853, 304631, 293984, 317630, 239944, 263915, 276828],
        [446956, 522704, 456870, 437822, 317125, 277446, 314615, 326350,
         310808, 271103, 337051, 328080, 351192, 262158, 286417, 303016],
        [417830, 456870, 472646, 409304, 292191, 256278, 288331, 302228,
         288518, 258125, 314909, 301162, 32

In [229]:
import concurrent

def put_arr(f_params):
    global var_arr
    i,j,k = f_params
    flagData_arr = []
    flagData_arr.append(var_arr[i])
    for l in range(0,4):
        flagData_arr.append(var_arr[l])
    flagData_arr.append(var_arr[j])
    flagData_arr.append(var_arr[k])
    return flagData_arr


def wtf(f_params):
    global var_arr
    i,j,k = f_params
    flagData_arr = []
    flagData_arr.append(var_arr[i])
    for l in range(0,4):
        flagData_arr.append(var_arr[l])
    flagData_arr.append(var_arr[j])
    flagData_arr.append(var_arr[k])
                
    #flagDataAcum.append(flagData_arr)
    flagDataCondVars = np.sum(reduce(lambda x,y:x*y, np.array(flagData_arr)))
                
    return flagDataCondVars

t_start = time.time()

#for  n_iter in range(0,100):    
#    with concurrent.futures.ThreadPoolExecutor(max_workers=4) as executor:
#        f_params =  [[x//(4*16),x//(16)%4,x%16] for x in list(range(0,192))]
#        results = np.asarray([*executor.map(wtf,f_params),]).reshape((3,4,16))
        
for  n_iter in range(0,100):    
    with concurrent.futures.ThreadPoolExecutor(max_workers=4) as executor:
        f_params =  [put_arr([x//(4*16),x//(16)%4,x%16]) for x in list(range(0,192))]
        results = np.asarray([*executor.map(lambda z:np.sum(reduce(lambda x,y:x*y, np.array(z))),f_params),]).reshape((3,4,16))
        
        
time.time()-t_start

27.688467979431152

In [227]:
results

array([[[482820, 408072, 415904, 396916, 276361, 264480, 301191, 267188,
         303419, 263966, 271340, 272660, 270449, 326657, 283238, 263447],
        [408072, 416340, 378740, 354824, 251299, 236898, 273999, 238286,
         276667, 231624, 246934, 240728, 242167, 293575, 256134, 233209],
        [415904, 378740, 431490, 367844, 246857, 241544, 279849, 242310,
         286709, 239176, 256364, 245606, 246563, 297885, 253948, 244717],
        [396916, 354824, 367844, 397836, 234937, 234126, 266909, 235372,
         276443, 227532, 242868, 243980, 225361, 285273, 254518, 227757]],

       [[408072, 416340, 378740, 354824, 251299, 236898, 273999, 238286,
         276667, 231624, 246934, 240728, 242167, 293575, 256134, 233209],
        [416340, 499878, 430694, 398770, 278491, 266166, 303963, 266366,
         316787, 255434, 285158, 264422, 272849, 319385, 286130, 260465],
        [378740, 430694, 437376, 369930, 248203, 241816, 283105, 241392,
         292249, 234850, 262108, 241050, 24

In [210]:
t_start = time.time()
result = np.apply_along_axis(arr=S,axis=3,func1d=np.sum((lambda z:reduce(lambda x,y:x*y,z))))
time.time()-t_start

AxisError: axis 3 is out of bounds for array of dimension 3

In [158]:
t_start = time.time()
result = np.apply_along_axis(arr=S,axis=3,func1d=np.multiply.reduce)
s_result = np.sum(result,axis=3)
time.time()-t_start

2.1360483169555664

In [139]:
np.einsum("ijkl->ijk",S.a)

array([[[13699., 13699., 13699., 13699., 13699., 13699., 13699., 13699.,
         13699., 13699., 13699., 13699., 13699., 13699., 13699., 13699.],
        [13699., 13699., 13699., 13699., 13699., 13699., 13699., 13699.,
         13699., 13699., 13699., 13699., 13699., 13699., 13699., 13699.],
        [13699., 13699., 13699., 13699., 13699., 13699., 13699., 13699.,
         13699., 13699., 13699., 13699., 13699., 13699., 13699., 13699.],
        [13699., 13699., 13699., 13699., 13699., 13699., 13699., 13699.,
         13699., 13699., 13699., 13699., 13699., 13699., 13699., 13699.]],

       [[13699., 13699., 13699., 13699., 13699., 13699., 13699., 13699.,
         13699., 13699., 13699., 13699., 13699., 13699., 13699., 13699.],
        [13699., 13699., 13699., 13699., 13699., 13699., 13699., 13699.,
         13699., 13699., 13699., 13699., 13699., 13699., 13699., 13699.],
        [13699., 13699., 13699., 13699., 13699., 13699., 13699., 13699.,
         13699., 13699., 13699., 13699., 13

In [125]:

flag_calc.shape

AttributeError: 'map' object has no attribute 'shape'

In [119]:
2%3

2

In [122]:
S_new = np.zeros((3,4,2**4))
for i in range(0,len(S)):
    a = i%3
    b = i%4
    c = i%(2**4)
    print(a,b,c)
    S_new[a][b][c] = S[i]

0 0 0


ValueError: setting an array element with a sequence.

In [73]:
S.sum(axis=0).shape

(4, 16)

In [99]:
(lambda x:np.sum(reduce(lambda y,z:y*z, x),axis=0))(flagDataAcum[0])

554545

In [93]:
S.shape

(3, 4, 16)

In [105]:
def sum_mul_f(arr):
    return (lambda x:np.sum(reduce(lambda y,z:y*z, x),axis=0))(arr)

In [106]:
sum_mul_f(flagDataAcum[0])

554545

In [249]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [294]:
from numba import njit
import random

@njit
def reduce_mul(arr):
    acc_np = np.ones(len(arr[0]))
    for i in range(0,len(arr)):
        for j in range(0,len(arr[i])):
            acc_np[j] = acc_np[j]*arr[i][j]
    return acc_np

@jit
def b_loops(var_arr):
    
    S = np.zeros((3,4,2**4)) # CANNOT BE OUT OF CONTEXT
    for n in range(0,100):
        S = np.zeros((3,4,2**4))
        for n in range(0,1):
            for i in range(0,3):
                for j in range(0,4):
                    for k in range(0,2**4):
                        flagData_arr = np.empty((7,1000))
                        flagData_arr[0]=np.array(var_arr[i])
                        for l in range(0,4):
                            flagData_arr[1+l]=np.array(var_arr[l])
                        flagData_arr[5] = np.array(var_arr[j])
                        flagData_arr[6] = np.array(var_arr[k])
                        flagDataCondVars = reduce_mul(flagData_arr)
                        S[i][j][k]=np.sum(flagDataCondVars)
    return S

# S = b_loops()

# S

In [295]:
var_arr = [[random.randint(0,4) for x in list(range(0,1000))] for y in list(range(0,20))]
S = b_loops(var_arr)

In [286]:
flagData_arr = np.empty((7,1000))
flagData_arr[0] = np.asarray(var_arr[0])

In [285]:
flagData_arr[1]

1000

In [297]:
%%time
S = b_loops(var_arr)

CPU times: user 12.1 s, sys: 62.7 ms, total: 12.2 s
Wall time: 12.1 s


In [305]:
for i in range(1,2**len([1,2,3,4])):
    print(bin(i)[::-1])

1b0
01b0
11b0
001b0
101b0
011b0
111b0
0001b0
1001b0
0101b0
1101b0
0011b0
1011b0
0111b0
1111b0


In [381]:
from multiprocessing import Pool, Lock, Semaphore

def f_w_lock(params):
    sub_params = params
    for i in range(0,sub_params[0]):
        #print(i)
        if (semaphore.get_value()==1):
            if i==sub_params[1]:
                #l.acquire()
                semaphore.acquire()
                print(i)
                semaphore.release()
                #l.release()
                return i
        else:
            return i

def init(l,s):
    global lock
    global semaphore
    lock = l
    semaphore = s
    
            
            

l = Lock()
s = Semaphore(1)
p = Pool(5,initializer=init,initargs=(l,s))
p.map(f_w_lock,[[10000,9000] for x in list(range(0,4))])
            
            

9000


[9000, 8669, 8248, 7930]

In [379]:
def f_test(a,b,c,d):
    return a+b+c+d
f_test(*([1,2,3]+[4]))

10

In [382]:
[1,2,3,4][1:]

[2, 3, 4]

In [26]:
action_types = [
    "app_custom_event.fb_mobile_achievement_unlocked",
"app_custom_event.fb_mobile_activate_app",
"app_custom_event.fb_mobile_add_payment_info",
"app_custom_event.fb_mobile_add_to_cart",
"app_custom_event.fb_mobile_add_to_wishlist",
"app_custom_event.fb_mobile_complete_registration",
"app_custom_event.fb_mobile_content_view",
"app_custom_event.fb_mobile_initiated_checkout",
"app_custom_event.fb_mobile_level_achieved",
"app_custom_event.fb_mobile_purchase",
"app_custom_event.fb_mobile_rate",
"app_custom_event.fb_mobile_search",
"app_custom_event.fb_mobile_spent_credits",
"app_custom_event.fb_mobile_tutorial_completion",
"app_use",
"checkin",
"comment",
"credit_spent",
"games.plays",
"landing_page_view",
"leadgen.other",
"like",
"link_click",
"mobile_app_install",
"offsite_conversion.fb_pixel_add_payment_info",
"offsite_conversion.fb_pixel_add_to_cart",
"offsite_conversion.fb_pixel_add_to_wishlist",
"offsite_conversion.fb_pixel_complete_registration",
"offsite_conversion.fb_pixel_custom",
"offsite_conversion.fb_pixel_initiate_checkout",
"offsite_conversion.fb_pixel_lead",
"offsite_conversion.fb_pixel_purchase",
"offsite_conversion.fb_pixel_search",
"offsite_conversion.fb_pixel_view_content",
"onsite_conversion.flow_complete",
"onsite_conversion.messaging_block",
"onsite_conversion.messaging_conversation_started_7d",
"onsite_conversion.messaging_first_reply",
"onsite_conversion.post_save",
"onsite_conversion.purchase",
"outbound_click",
"photo_view",
"post",
"post_reaction",
"rsvp",
"video_view",
"app_engagement",
"app_story",
"page_engagement",
"page_story",
"post_engagement",
"instagram_profile_engagement",
"post_story",
"offsite_conversion",
"onsite_conversion",
"app_custom_event",
"onsite_web_app_event",
"mobile_app_retention",
"mobile_app_roas",
"offsite_engagement",
"store_visit_with_dwell",
"add_to_cart",
"onsite_app_add_to_cart",
"onsite_web_add_to_cart",
"onsite_web_app_add_to_cart",
"complete_registration",
"purchase",
"onsite_app_purchase",
"onsite_web_purchase",
"onsite_web_app_purchase",
"search",
"view_content",
"onsite_app_view_content",
"onsite_web_view_content",
"onsite_web_app_view_content",
"initiate_checkout",
"add_payment_info",
"add_to_wishlist",
"lead",
"omni_app_install",
"omni_purchase",
"omni_custom",
"subscribe",
]

list_fields =  [
    'actions',
    'action_values',
    'cost_per_10_sec_video_view',
    'cost_per_action_type',
    'cost_per_unique_action_type',
    'cost_per_outbound_click',
    'cost_per_unique_outbound_click',
    'outbound_clicks_ctr',
    'purchase_roas',
    'mobile_app_purchase_roas',
    'outbound_clicks',
    'cost_per_thruplay',
    'unique_actions',
    'unique_outbound_clicks',
    'unique_outbound_clicks_ctr',
    'video_10_sec_watched_actions',
    'video_30_sec_watched_actions',
    'video_avg_percent_watched_actions',
    'video_avg_time_watched_actions',
    'video_p100_watched_actions',
    'video_p25_watched_actions',
    'video_p50_watched_actions',
    'video_p75_watched_actions',
    'video_p95_watched_actions',
    'video_play_actions',
    'video_thruplay_watched_actions',
    'website_ctr',
    'website_purchase_roas'
]

In [28]:
len(list_fields)

28

In [24]:
action_types[45]

'video_view'

In [27]:
for list_field in list_fields:
    print("/*List field :", list_field+" */")
    for action_type in action_types:
        print("fields.newMetric()\n\t   .setId('"+list_field+"__"+action_type+"')\n\
              .setName('"+str.upper(list_field[0])+list_field[1:]+"__"+action_type+"')\n\
              .setType(types.NUMBER)\n\
              .setAggregation(aggregations.SUM);")
        print("\n")
    print("/*END List field :", list_field+" */")

/*List field : actions */
fields.newMetric()
	   .setId('actions__app_custom_event.fb_mobile_achievement_unlocked')
              .setName('Actions__app_custom_event.fb_mobile_achievement_unlocked')
              .setType(types.NUMBER)
              .setAggregation(aggregations.SUM);


fields.newMetric()
	   .setId('actions__app_custom_event.fb_mobile_activate_app')
              .setName('Actions__app_custom_event.fb_mobile_activate_app')
              .setType(types.NUMBER)
              .setAggregation(aggregations.SUM);


fields.newMetric()
	   .setId('actions__app_custom_event.fb_mobile_add_payment_info')
              .setName('Actions__app_custom_event.fb_mobile_add_payment_info')
              .setType(types.NUMBER)
              .setAggregation(aggregations.SUM);


fields.newMetric()
	   .setId('actions__app_custom_event.fb_mobile_add_to_cart')
              .setName('Actions__app_custom_event.fb_mobile_add_to_cart')
              .setType(types.NUMBER)
              .setAggre



fields.newMetric()
	   .setId('cost_per_thruplay__app_custom_event.fb_mobile_add_to_wishlist')
              .setName('Cost_per_thruplay__app_custom_event.fb_mobile_add_to_wishlist')
              .setType(types.NUMBER)
              .setAggregation(aggregations.SUM);


fields.newMetric()
	   .setId('cost_per_thruplay__app_custom_event.fb_mobile_complete_registration')
              .setName('Cost_per_thruplay__app_custom_event.fb_mobile_complete_registration')
              .setType(types.NUMBER)
              .setAggregation(aggregations.SUM);


fields.newMetric()
	   .setId('cost_per_thruplay__app_custom_event.fb_mobile_content_view')
              .setName('Cost_per_thruplay__app_custom_event.fb_mobile_content_view')
              .setType(types.NUMBER)
              .setAggregation(aggregations.SUM);


fields.newMetric()
	   .setId('cost_per_thruplay__app_custom_event.fb_mobile_initiated_checkout')
              .setName('Cost_per_thruplay__app_custom_event.fb_mobile_initiated_c



fields.newMetric()
	   .setId('unique_outbound_clicks_ctr__mobile_app_retention')
              .setName('Unique_outbound_clicks_ctr__mobile_app_retention')
              .setType(types.NUMBER)
              .setAggregation(aggregations.SUM);


fields.newMetric()
	   .setId('unique_outbound_clicks_ctr__mobile_app_roas')
              .setName('Unique_outbound_clicks_ctr__mobile_app_roas')
              .setType(types.NUMBER)
              .setAggregation(aggregations.SUM);


fields.newMetric()
	   .setId('unique_outbound_clicks_ctr__offsite_engagement')
              .setName('Unique_outbound_clicks_ctr__offsite_engagement')
              .setType(types.NUMBER)
              .setAggregation(aggregations.SUM);


fields.newMetric()
	   .setId('unique_outbound_clicks_ctr__store_visit_with_dwell')
              .setName('Unique_outbound_clicks_ctr__store_visit_with_dwell')
              .setType(types.NUMBER)
              .setAggregation(aggregations.SUM);


fields.newMetric()
	   .setI

fields.newMetric()
	   .setId('video_p75_watched_actions__onsite_web_purchase')
              .setName('Video_p75_watched_actions__onsite_web_purchase')
              .setType(types.NUMBER)
              .setAggregation(aggregations.SUM);


fields.newMetric()
	   .setId('video_p75_watched_actions__onsite_web_app_purchase')
              .setName('Video_p75_watched_actions__onsite_web_app_purchase')
              .setType(types.NUMBER)
              .setAggregation(aggregations.SUM);


fields.newMetric()
	   .setId('video_p75_watched_actions__search')
              .setName('Video_p75_watched_actions__search')
              .setType(types.NUMBER)
              .setAggregation(aggregations.SUM);


fields.newMetric()
	   .setId('video_p75_watched_actions__view_content')
              .setName('Video_p75_watched_actions__view_content')
              .setType(types.NUMBER)
              .setAggregation(aggregations.SUM);


fields.newMetric()
	   .setId('video_p75_watched_actions__onsite_app